### ISSUE TITLE
Adjust height for each slide

### ISSUE THREAD

**Issue by agutiernc** [blaze-slider/blaze-slider#47]
Is there a way to adjust the height for each slide depending on content?

When I target .blaze-track in a CSS file, I can change the height, but all the slides are the same height.
I also tried  targeting each slide div with different heights, but it doesn't work.

I'm trying to implement this in React. Having a height auto feature for each individual slide would help.

**Comment by erikyo** [comment]
@agutiernc the flex cs property already sets the same height for blaze-track children, I think you are referring to images placed inside the slide div. In this case you must set the image css like below>

```css
.blaze-slider .blaze-track > div img {
    height: 100%;
    -o-object-fit: cover;
    object-fit: cover;
}
```

hope it helps!
